In [1]:
import pandas as pd
import numpy as np

data = {
    "Name": ["Aman", "Riya", "Karan", "Neha", "Pooja", "Rohit"],
    "Department": ["Sales", "HR", "Sales", "IT", "HR", "IT"],
    "Salary": [45000, 52000, 47000, 60000, np.nan, 58000],
    "Experience": [2, 4, 3, 5, 2, 4],
    "Rating": [4.2, 4.8, 4.1, 4.9, 4.0, np.nan]
}

df = pd.DataFrame(data)
df

    Name Department   Salary  Experience  Rating
0   Aman      Sales  45000.0           2     4.2
1   Riya         HR  52000.0           4     4.8
2  Karan      Sales  47000.0           3     4.1
3   Neha         IT  60000.0           5     4.9
4  Pooja         HR      NaN           2     4.0
5  Rohit         IT  58000.0           4     NaN

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        6 non-null      object
 1   Department  6 non-null      object
 2   Salary      5 non-null      float64
 3   Experience  6 non-null      int64
 4   Rating      5 non-null      float64
dtypes: float64(2), int64(1), object(2)
memory usage: 372.0+ bytes

In [3]:
df.head(4)# use to displaytop rows of the data frame

    Name Department   Salary  Experience  Rating
0   Aman      Sales  45000.0           2     4.2
1   Riya         HR  52000.0           4     4.8
2  Karan      Sales  47000.0           3     4.1
3   Neha         IT  60000.0           5     4.9

In [4]:
df.tail(2)
# tail(no of row)- used to display last rows of the dataframe

    Name Department   Salary  Experience  Rating
4  Pooja         HR      NaN           2     4.0
5  Rohit         IT  58000.0           4     NaN

In [5]:
# display number of row and column
df.shape
# sape - (attribute) which return no of rows and columns

(6, 5)

In [6]:
# show all column name
# columns = (attribute) which return column names in the list

In [7]:
# check data type of each column
df.dtypes
# datatype= (attribute) which returns data type of each column

Name           object
Department     object
Salary        float64
Experience      int64
Rating        float64
dtype: object

In [8]:
# finde total no of missing in each collumn
df.isnull().sum()

Name          0
Department    0
Salary        1
Experience    0
Rating        1
dtype: int64

df.

In [9]:
# display only name and salary column

In [10]:
# show salary more than 50000
df.groupby("Name")["Salary"].max()

Name
Aman     45000.0
Karan    47000.0
Neha     60000.0
Pooja        NaN
Riya     52000.0
Rohit    58000.0
Name: Salary, dtype: float64

In [11]:
# show employee from hr department

In [12]:
# finde maximum salary in the data set

In [13]:
# qu. total missing in each column
df.isnull().sum()

Name          0
Department    0
Salary        1
Experience    0
Rating        1
dtype: int64

In [14]:
# isnull() is used to check value is null or not it return answer in true false
# isnull ().sum( is used to check column wise null valus

In [15]:
# fell measing salary using avarage salary

In [16]:
# describe () = it is method which returns all statical info of the numerical column

In [17]:
# Q.missing value only in salary
salary_null = df(df['salary'].isnull()]
salary_null

SyntaxError: closing parenthesis ']' does not match opening parenthesis '(' (90196252.py, line 2)

In [ ]:
# q fill missing the salary with mean
df['Salary'].fillna(df['Salary'].mean(), inplace =True)
df

In [ ]:
# Q. fill missing rating with mean
df['Rating'].fillna(df['Rating'].mean(), inplace = True)
df

In [ ]:
#Q. show name and salary columns
df[["Name","Salary"]]

In [ ]:
# Q. employee from HR department
df[df['Department'] =='HR']

In [ ]:
# employee with 4 or more experience
df[df['Experience'] >=4]

In [ ]:
# create bonus column((10%)
df['Bonus'] = df['Salary'] *0.1

In [ ]:
# Q. salary salary between  45000 and 58000

df[(df['Salary'] >= 45000) & (df['Salary'] <= 58000)]

In [ ]:
# create columns total package
df["total_package"] = df["Salary"]+df["Bonus"]
df

In [ ]:
# create columns total package
df["total_package"] = df["Salary"] = df["Bonus"]
df

In [19]:
#Q. sorting salary in descending order
df.sort_values(by="Salary" , ascending=False)

    Name Department   Salary  Experience  Rating
3   Neha         IT  60000.0           5     4.9
5  Rohit         IT  58000.0           4     NaN
1   Riya         HR  52000.0           4     4.8
2  Karan      Sales  47000.0           3     4.1
0   Aman      Sales  45000.0           2     4.2
4  Pooja         HR      NaN           2     4.0

In [20]:
# top 2 highest salary employees
df.nlargest(2, "Salary")

    Name Department   Salary  Experience  Rating
3   Neha         IT  60000.0           5     4.9
5  Rohit         IT  58000.0           4     NaN

In [22]:
# employees is highest salary
df.loc[df['Salary'].idxmax()]

Name             Neha
Department         IT
Salary        60000.0
Experience          5
Rating            4.9
Name: 3, dtype: object

In [23]:
# count dept wise
df['Department'].value_counts()

Department
Sales    2
HR       2
IT       2
Name: count, dtype: int64

In [24]:
df.groupby("Department")["Name"].count()

Department
HR       2
IT       2
Sales    2
Name: Name, dtype: int64

In [25]:
# dept wise average rating
df.groupby("Department")["Rating"].mean()

Department
HR       4.40
IT       4.90
Sales    4.15
Name: Rating, dtype: float64