In [1]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\hp\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\hp\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

In [3]:
data = [10,2,30,40]
s = pd.Series(data)
s

0    10
1     2
2    30
3    40
dtype: int64

In [4]:
# custom index
s = pd.Series([10,20,30], index = ["a","b", "c"])
s

a    10
b    20
c    30
dtype: int64

In [5]:
# create series from dictionary
data ={
    "A" : 10,
    "B" : 20,
    "C" : 30
}
s = pd.Series(data)
s

A    10
B    20
C    30
dtype: int64

In [6]:
# access data in Series

In [7]:
# 1 using index
print(s[0])

10

C:\Users\HP\AppData\Local\Temp\ipykernel_8804\2138904547.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[0])

In [8]:
# 2 . using label
print(s["C"])

30

In [9]:
# slicing
s = pd.Series([10,20,30,40,50,60])
print(s[1:4])

1    20
2    30
3    40
dtype: int64

In [10]:
# operation  on Series

In [11]:
# mathematical operation
s = pd.Series([1,2,3])
print(s + 10)

0    11
1    12
2    13
dtype: int64

In [12]:
# conditional filtering
s = pd.Series([1,2,3,4,5,6,7,8,9,10])
print(s[s%2==0])

1     2
3     4
5     6
7     8
9    10
dtype: int64

In [13]:
# atributes
print("Index:" , s.index)

Index: RangeIndex(start=0, stop=10, step=1)

In [14]:
s.values # values present in series

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
s.dtype # no of elements

dtype('int64')

In [16]:
s.shape # no of element

(10,)

In [17]:
s = pd.Series([1,5,15,20])
print(s[1:4])

1     5
2    15
3    20
dtype: int64

In [18]:
df = pd.DataFrame(
     {
       "ID" :[101,102,103],
       "Name":["Anuj", "Nitin","Pooja"]
     }
)
df

    ID   Name
0  101   Anuj
1  102  Nitin
2  103  Pooja

In [19]:
# from list
data =  [[1,"A"],[2,"B"]]
pd.DataFrame(data,columns=['ID','Name'])

   ID Name
0   1    A
1   2    B

In [22]:
df = pd.read_excel("sample.xlsx")
df

   Unnamed: 0  product  price  quantity
0           0      pen     10         4
1           1   pencil      5         5
2           2     book     45         6
3           3  notbook     24         2
4           4      PEN     20         2