In [1]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\hp\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\hp\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

In [3]:
data = [10,2,30,40]
s = pd.Series(data)
s

0    10
1     2
2    30
3    40
dtype: int64

In [4]:
# custom index
s = pd.Series([10,20,30], index = ["a","b", "c"])
s

a    10
b    20
c    30
dtype: int64

In [5]:
# create series from dictionary
data ={
    "A" : 10,
    "B" : 20,
    "C" : 30
}
s = pd.Series(data)
s

A    10
B    20
C    30
dtype: int64

In [6]:
# access data in Series

In [7]:
# 1 using index
print(s[0])

10

C:\Users\HP\AppData\Local\Temp\ipykernel_10956\2138904547.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[0])

In [8]:
# 2 . using label
print(s["C"])

30

In [9]:
# slicing
s = pd.Series([10,20,30,40,50,60])
print(s[1:4])

1    20
2    30
3    40
dtype: int64

In [10]:
# operation  on Series

In [11]:
# mathematical operation
s = pd.Series([1,2,3])
print(s + 10)

0    11
1    12
2    13
dtype: int64

In [12]:
# conditional filtering
s = pd.Series([1,2,3,4,5,6,7,8,9,10])
print(s[s%2==0])

1     2
3     4
5     6
7     8
9    10
dtype: int64

In [13]:
# atributes
print("Index:" , s.index)

Index: RangeIndex(start=0, stop=10, step=1)

In [14]:
s.values # values present in series

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
s.dtype # no of elements

dtype('int64')

In [16]:
s.shape # no of element

(10,)

In [17]:
s = pd.Series([1,5,15,20])
print(s[1:4])

1     5
2    15
3    20
dtype: int64

In [18]:
df = pd.DataFrame(
     {
       "ID" :[101,102,103],
       "Name":["Anuj", "Nitin","Pooja"]
     }
)
df

    ID   Name
0  101   Anuj
1  102  Nitin
2  103  Pooja

In [19]:
# from list
data =  [[1,"A"],[2,"B"]]
pd.DataFrame(data,columns=['ID','Name'])

   ID Name
0   1    A
1   2    B

In [3]:
df = pd.read_excel("sample.excel")
df

NameError: name 'df' is not defined

In [1]:
import numpy as np
import pandas as pd
data = {
    "Nmae":["Amit","Riya", "John","Sara"],
    "Age" :[23,np.nan,30,np.nan],
    "Salary":[20000,30000,np.nan,40000],
    "City":["Pune","Mumbai", None,"Delhi"]
}
df = pd.DataFrame(data)
df

   Nmae   Age   Salary    City
0  Amit  23.0  20000.0    Pune
1  Riya   NaN  30000.0  Mumbai
2  John  30.0      NaN    None
3  Sara   NaN  40000.0   Delhi

In [1]:
# check  null values
df.isnull()

NameError: name 'df' is not defined

In [ ]:
df.isnull().sum()

In [1]:
df['Age'].fillna(df['Age'].median(),inplace = True)
df

NameError: name 'df' is not defined

In [1]:
df['Age'] = df['Age'].astype(int)
df

NameError: name 'df' is not defined

In [5]:
df=['Salary'].fillna(df['Salary'].mean(),inplace=True)
df

AttributeError: 'list' object has no attribute 'fillna'

In [6]:
df["City"].fillna("Unknown",inplace=True)
df

NameError: name 'df' is not defined

In [7]:
df.to_csv("Sample_emp.csv",index=False)

NameError: name 'df' is not defined

In [ ]:
import pandas as pd


data = {
    "Name": ["Ankita","Rahul","Ankita","Sneha","Rahul","Ankita"],
    "Age":[22,25,22,23,25,22],
    "City":["Pune","Mumbai","Pune","Delhi","Mumbai","Pune"]
}

df = pd.DataFrame(data)
print(df)

In [ ]:
# finde duplicates
df.duplicated()

In [ ]:
# show only duplicate
df[df.duplicated()]

In [ ]:
# remove duplicates

df_clean = df.drop_duplicates()
print(df_clean)

In [24]:
# Groupby
import pandas as pd

In [26]:
data = {
    "Name":["Arjun", "Rahul", "Sneha","Amit","Pooja"],
    "Dept":["IT","HR","IT","HR","IT"],
    "Salary":[50000,400000,600000,3400000,230000]
}
df = pd.DataFrame(data)
print(df)

    Name Dept   Salary
0  Arjun   IT    50000
1  Rahul   HR   400000
2  Sneha   IT   600000
3   Amit   HR  3400000
4  Pooja   IT   230000

In [28]:
df.groupby("Dept")["Salary"].sum()

Dept
HR    3800000
IT     880000
Name: Salary, dtype: int64

In [29]:
df.groupby("Dept")["Salary"].mean()

Dept
HR    1.900000e+06
IT    2.933333e+05
Name: Salary, dtype: float64

In [32]:
df.groupby("Dept")["Salary"].agg(["mean","sum","max"])

              mean      sum      max
Dept
HR    1.900000e+06  3800000  3400000
IT    2.933333e+05   880000   600000

In [ ]:
## pivote table

data = {
    "Name":["Arjun", "Rahul", "Sneha","Amit","Pooja"],
    "Dept":["IT","HR","IT","HR","IT"],
    "Gender":["M","M","F","M","F"],
    "Salary":[50000,400000,600000,3400000,230000]
}
df = pd.DataFrame(data)
print(df)

In [ ]:
pd.pivot_table(df,values = "Salary", index = "Dept")

In [45]:
pd.pivot_table(df,values = "Salary" , index = "Dept",columns = "Gender")

Gender         F          M
Dept
HR           NaN  1900000.0
IT      415000.0    50000.0

In [46]:
pd.pivot_table(df,values = "Salary" , index= "Dept", aggfunc = ["mean","sum"])

              mean      sum
            Salary   Salary
Dept
HR    1.900000e+06  3800000
IT    2.933333e+05   880000

In [47]:
pd.pivot_table(df,values = "Salary" , index="Dept", columns="Gender",fill_value =0)

Gender         F          M
Dept
HR           0.0  1900000.0
IT      415000.0    50000.0

## MERGING AND JOINING

In [58]:
df1 = pd.DataFrame({
    "ID":[1,2,3],
    "Name":["Arjun","Rahul","Sneha"]
})
df2 = pd.DataFrame({
    "ID":[1,2,3],
    "Salary":[20000,20000,30000]
})
df1
df2

   ID  Salary
0   1   20000
1   2   20000
2   3   30000

In [54]:
# 1. inner join - only matching records
pd.merge(df1,df2,on= "ID")

   ID   Name  Salary
0   1  Arjun   20000
1   2  Rahul   20000
2   3  Sneha   40000

In [56]:
# 2. left join - all rows from left table
pd.merge(df1,df2,on="ID",how="left")

   ID   Name  Salary
0   1  Arjun   20000
1   2  Rahul   20000
2   3  Sneha   40000

In [62]:
# right join - all row from right table
pd.merge(df1,df2,on="ID" , how = "right")

   ID   Name  Salary
0   1  Arjun   20000
1   2  Rahul   20000
2   3  Sneha   30000

In [64]:
# outer join - all rows from from both tables
pd.merge(df1,df2,on="ID" ,how= "outer")

   ID   Name  Salary
0   1  Arjun   20000
1   2  Rahul   20000
2   3  Sneha   30000

In [4]:
# join
df1 = pd.DataFrame({
    "Name":["Arjun","Rahul","Sneha"]
}, index = [1,2,3])

df2 = pd.DataFrame({
    "Salary":[50000,40000,60000]
},index = [1,2,4])
df1
df2

   Salary
1   50000
2   40000
4   60000

In [5]:
# left join
df1.join(df2,how = "left")

    Name   Salary
1  Arjun  50000.0
2  Rahul  40000.0
3  Sneha      NaN

In [7]:
# right join
df1.join(df2,how = "right")

    Name  Salary
1  Arjun   50000
2  Rahul   40000

In [8]:
# inner join
df1.join(df2,how = "inner")

    Name  Salary
1  Arjun   50000
2  Rahul   40000

In [9]:
# outer join
df1.join(df2,how = "outer")

    Name   Salary
1  Arjun  50000.0
2  Rahul  40000.0
3  Sneha      NaN
4    NaN  60000.0

In [10]:
# apply() - works on rows or columns
# map() - works on single columns
# lambad() - small inline function

In [14]:
data = {
    "Name":["Arjun","Rahul","Sneha","Amit","Pooja"],
    "Dept":["IT","HR","IT", "HR","IT"],
    "Salary":[50000,30000,40000,50000,20000]
}
df = pd.DataFrame(data)
print(df)

    Name Dept  Salary
0  Arjun   IT   50000
1  Rahul   HR   30000
2  Sneha   IT   40000
3   Amit   HR   50000
4  Pooja   IT   20000

In [20]:
df["Salary"] =df["Salary"].apply(lambda x:x+50000)
df

    Name Dept  Salary
0  Arjun   IT  100000
1  Rahul   HR   80000
2  Sneha   IT   90000
3   Amit   HR  100000
4  Pooja   IT   70000

In [24]:
df["Bonus"]= df.apply(lambda x:x["Salary"]*0.1,axis=1)
df

    Name Dept  Salary    Bonus
0  Arjun   IT  100000  10000.0
1  Rahul   HR   80000   8000.0
2  Sneha   IT   90000   9000.0
3   Amit   HR  100000  10000.0
4  Pooja   IT   70000   7000.0

In [28]:
def Category(Salary):
    if Salary > 50000:
       return "High"
    else:
       return "Law"
df['Category']=df['Salary'].apply(Category)
df

    Name Dept  Salary    Bonus Category
0  Arjun   IT  100000  10000.0     High
1  Rahul   HR   80000   8000.0     High
2  Sneha   IT   90000   9000.0     High
3   Amit   HR  100000  10000.0     High
4  Pooja   IT   70000   7000.0     High